package highlights

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"os"
	"path/filepath"
	"strings"
	"syscall"

	"github.com/northbright/ffcmd"
	"github.com/northbright/timestamp"
)

var (
	DefaultFPS            = 25
	DefaultEncoder string = "libx264"
	DefaultPreset  string = "medium"
)

// ImageClip represents the video clip generated by an image.
type ImageClip struct {
	File            string `json:"file"`
	Duration        int    `json:"duration"`
	FadeOutDuration int    `json:"fade_out_duration"`
	Subtitle        string `json:"subtitle"`
	FontSize        int    `json:"font_size"`
}

// Clip represents the video clip.
type Clip struct {
	File     string `json:"file"`
	Start    string `json:"start"`
	End      string `json:"end"`
	Subtitle string `json:"subtitle"`
	FontSize int    `json:"font_size"`
}

// Output represents the output information.
type Output struct {
	File    string `json:"file"`
	W       int    `json:"w"`
	H       int    `json:"h"`
	FPS     int    `json:"fps"`
	Encoder string `jsong:"encoder"`
	CRF     int    `json:"crf"`
	Preset  string `json:"preset"`
}

// Highlights is the video maker to generate highlights videos.
type Highlights struct {
	OP    *ImageClip `json:"op"`
	ED    *ImageClip `json:"ed"`
	Clips []*Clip    `json:"clips"`
	BGMs  []string   `json:"bgms"`
	// Add rank prefix(No.XX).
	AddRankPrefix     bool    `json:"add_rank_prefix"`
	KeepOriginalAudio bool    `json:"keep_original_audio"`
	Out               *Output `json:"output"`
	ffmpeg            *ffcmd.FFmpegCmd
	concatFC          *ffcmd.FilterChain
}

// isEncoderValid checks if FPS is valid.
func isFPSValid(fps int) bool {
	if fps <= 0 {
		return false
	}

	return true
}

// isEncoderValid checks if encoder is valid.
func isEncoderValid(enc string) bool {
	m := map[string]struct{}{
		"libx264": struct{}{},
		"libx265": struct{}{},
	}

	_, ok := m[enc]
	return ok
}

// isCRFValid checks if CRF is valid when encoding H.264 / H.265 video.
func isCRFValid(crf int) bool {
	if crf < 17 || crf > 51 {
		return false
	}

	return true
}

// isPresetValid checks if preset is valid when encoding H.264 / H.265 video.
func isPresetValid(preset string) bool {
	m := map[string]struct{}{
		"ultrafast": struct{}{},
		"superfast": struct{}{},
		"veryfast":  struct{}{},
		"faster":    struct{}{},
		"fast":      struct{}{},
		"medium":    struct{}{},
		"slow":      struct{}{},
		"slower":    struct{}{},
		"veryslow":  struct{}{},
	}

	_, ok := m[preset]

	return ok
}

// Load returns an Highlights by reading a byte slice which contains JSON encoded data.
func Load(buf []byte) (*Highlights, error) {
	h := &Highlights{}

	if err := json.Unmarshal(buf, h); err != nil {
		return nil, err
	}

	// Check FPS
	if !isFPSValid(h.Out.FPS) {
		h.Out.FPS = DefaultFPS
	}

	// Check encoder.
	if !isEncoderValid(h.Out.Encoder) {
		h.Out.Encoder = DefaultEncoder
	}

	// Check CRF.
	if !isCRFValid(h.Out.CRF) {
		if h.Out.Encoder == "libx264" {
			// Default CRF is 23 for H.264
			h.Out.CRF = 23
		} else {
			// Default CRF is 28 for H.265
			h.Out.CRF = 28
		}
	}

	// Check preset.
	if !isPresetValid(h.Out.Preset) {
		h.Out.Preset = DefaultPreset
	}

	// Create ffmpeg command with output file.
	options := []string{
		fmt.Sprintf("-r %d", h.Out.FPS),
		fmt.Sprintf("-c:v %s", h.Out.Encoder),
		fmt.Sprintf("-crf %d", h.Out.CRF),
		fmt.Sprintf("-preset %s", h.Out.Preset),
		"-shortest",
	}

	h.ffmpeg = ffcmd.NewFFmpegCmd(h.Out.File, true, options...)

	outputLabels := []string{"[outv]"}
	if h.KeepOriginalAudio || len(h.BGMs) == 0 {
		outputLabels = append(outputLabels, "[outa]")
	}

	// Create concat filterchain.
	h.concatFC = ffcmd.NewFilterChain(outputLabels...)

	return h, nil
}

// LoadJSON returns an Highlights by reading a JSON file.
func LoadJSON(f string) (*Highlights, error) {
	buf, err := os.ReadFile(f)
	if err != nil {
		return nil, err
	}

	return Load(buf)
}

// addImageClip adds an image clip to the highlights video.
// ic: image clip to add.
// name: name of the image clip which will be used as the output label(no need to add "[]").
func (h *Highlights) addImageClip(ic *ImageClip, name string) error {
	if ic.File == "" {
		return fmt.Errorf("image clip's file is empty")
	}

	if name == "" {
		return fmt.Errorf("empty image clip name")
	}

	fps := fmt.Sprintf("fps=%d", h.Out.FPS)
	loop := fmt.Sprintf("loop=loop=%d:size=1", ic.Duration*h.Out.FPS)
	scale := fmt.Sprintf("scale=%d:%d:force_original_aspect_ratio=decrease", h.Out.W, h.Out.H)
	pad := fmt.Sprintf("pad=%d:%d:(ow-iw)/2:(oh-ih)/2", h.Out.W, h.Out.H)
	setsar := "setsar=1:1"
	format := "format=pix_fmts=yuv420p"

	// Create video filterchain.
	v := ffcmd.NewFilterChain(fmt.Sprintf("[%s_v]", name))

	// Add image file as ffmpeg input and get the input index.
	// Add video stream of image([0:v:0]) as video filterchain's input.
	v.AddInputByID(h.ffmpeg.AddInput(ic.File), "v", 0)

	// Chain video filters.
	v.Chain(fps).Chain(loop).Chain(scale).Chain(pad).Chain(setsar).Chain(format)

	// Check if need to chain subtitles filter.
	if ic.Subtitle != "" {
		srtFile := strings.Replace(ic.File, filepath.Ext(ic.File), ".srt", -1)
		createCmd, err := ffcmd.NewCreateOneSubSRTCmdForImageClip(srtFile, ic.Subtitle, float32(ic.Duration))
		if err != nil {
			log.Printf("ffcmd.NewCreateOneSubSRTCmdForImageClip() error: %v", err)
			return err
		}
		// Add command to create SRT file as ffmpeg's pre-commands(set-up commmands).
		h.ffmpeg.AddPreCmd(createCmd)

		removeCmd, err := ffcmd.NewRemoveOneSubSRTCmd(srtFile)
		if err != nil {
			log.Printf("ffcmd.NewRemoveOneSubSRTCmd() error: %v", err)
			return err
		}
		// Add command to remove created file as ffmpeg's post-commands(clean-up commands).
		h.ffmpeg.AddPostCmd(removeCmd)

		// Create and chain subtitles filter.
		subtitles := fmt.Sprintf("subtitles='%s':force_style='Fontsize=%d'", srtFile, ic.FontSize)
		v.Chain(subtitles)
	}

	// Chain fade filter.
	fade := fmt.Sprintf("fade=t=out:st=%d:d=%d", ic.Duration-ic.FadeOutDuration, ic.FadeOutDuration)
	v.Chain(fade)

	// Add video filterchain to filtergraph.
	h.ffmpeg.Chain(v)

	// Add image clip's video filterchain's output as concat filterchain's input.
	h.concatFC.AddInputByOutput(v, 0)

	if h.KeepOriginalAudio || len(h.BGMs) == 0 {
		// Create audio filterchain.
		a := ffcmd.NewFilterChain(fmt.Sprintf("[%s_a]", name))

		// Create audio filters.
		aevalsrc := fmt.Sprintf("aevalsrc=0:d=%d", ic.Duration)

		// Chain audio filters.
		a.Chain(aevalsrc)

		// Add audio filterchain to filtergraph.
		h.ffmpeg.Chain(a)

		// Add image clip's audio filterchain's output as concat filterchain's input.
		h.concatFC.AddInputByOutput(a, 0)
	}

	return nil
}

// FFmpegCmd returns a ffcmd.FFmpegCmd to run.
func (h *Highlights) FFmpegCmd() (*ffcmd.FFmpegCmd, error) {
	// Segments count to concat.
	n := 0

	// Add OP.
	if err := h.addImageClip(h.OP, "op"); err != nil {
		return nil, fmt.Errorf("add OP error: %v", err)
	}
	n += 1

	clipNum := len(h.Clips)

	// Add video clips.
	for i, c := range h.Clips {
		// Create clip video filterchain.
		clip_v := ffcmd.NewFilterChain(fmt.Sprintf("[clip_%02d_v]", i))

		// Create clip audio filterchain.
		clip_a := ffcmd.NewFilterChain(fmt.Sprintf("[clip_%02d_a]", i))

		// Add video file as ffmpeg input and get the input index.
		// Add video / audio stream of the file([X:v:0] / [X:a:0], X is the ffmpeg input id) as clip's input.
		id := h.ffmpeg.AddInput(c.File)
		clip_v.AddInputByID(id, "v", 0)
		clip_a.AddInputByID(id, "a", 0)

		// Create and chain scale, pad, setsar filters.
		scale := fmt.Sprintf("scale=%d:%d:force_original_aspect_ratio=decrease", h.Out.W, h.Out.H)
		pad := fmt.Sprintf("pad=%d:%d:(ow-iw)/2:(oh-ih)/2", h.Out.W, h.Out.H)
		setsar := "setsar=1:1"

		clip_v.Chain(scale).Chain(pad).Chain(setsar)

		// Check if need to chain trim, setpts / atrim, asetpts filter.
		if c.Start != c.End {
			// Create clip video / audio filters.
			trim := "trim="
			atrim := "atrim="

			if c.Start != "" {
				start, err := timestamp.New(c.Start)
				if err != nil {
					log.Printf("get start timestamp error: %v, c.Start = %s", err, c.Start)
					return nil, err
				}
				trim += fmt.Sprintf("start=%s:", start.SecondStr())
				atrim += fmt.Sprintf("start=%s:", start.SecondStr())
			}

			if c.End != "" {
				end, err := timestamp.New(c.End)
				if err != nil {
					log.Printf("get end timestamp error: %v, c.End = %s", err, c.End)
					return nil, err
				}
				trim += fmt.Sprintf("end=%s", end.SecondStr())
				atrim += fmt.Sprintf("end=%s", end.SecondStr())
			} else {
				trim = strings.TrimSuffix(trim, ":")
				atrim = strings.TrimSuffix(atrim, ":")
			}

			setpts := "setpts=PTS-STARTPTS"

			// Chain trim and setpts filter.
			clip_v.Chain(trim).Chain(setpts)

			asetpts := "asetpts=PTS-STARTPTS"

			// Chain atrim and asetpts filter.
			clip_a.Chain(atrim).Chain(asetpts)
		}

		// Check if need to chain subtitles filter.
		if c.Subtitle != "" {
			srtFile := strings.Replace(c.File, filepath.Ext(c.File), ".srt", -1)
			text := c.Subtitle
			if h.AddRankPrefix {
				text = fmt.Sprintf("No.%d %s", clipNum-i, c.Subtitle)
			}
			createCmd, err := ffcmd.NewCreateOneSubSRTCmd(srtFile, c.File, text, c.Start, c.End)
			if err != nil {
				log.Printf("ffcmd.NewCreateOneSubSRTCmd() error: %v", err)
				return nil, err
			}
			// Add command to create SRT file as ffmpeg's pre-commands(set-up commmands).
			h.ffmpeg.AddPreCmd(createCmd)

			removeCmd, err := ffcmd.NewRemoveOneSubSRTCmd(srtFile)
			if err != nil {
				log.Printf("ffcmd.NewRemoveOneSubSRTCmd() error: %v", err)
				return nil, err
			}
			// Add command to remove created file as ffmpeg's post-commands(clean-up commands).
			h.ffmpeg.AddPostCmd(removeCmd)

			// Create and chain subtitles filter.
			subtitles := fmt.Sprintf("subtitles='%s':force_style='Fontsize=%d'", srtFile, c.FontSize)
			clip_v.Chain(subtitles)
		}

		// Add clip video filterchain to filtergraph.
		h.ffmpeg.Chain(clip_v)
		// Add clip video filterchain's output as concat filterchain's input.
		h.concatFC.AddInputByOutput(clip_v, 0)

		if h.KeepOriginalAudio || len(h.BGMs) == 0 {
			// Add clip audio filterchain to filtergraph.
			h.ffmpeg.Chain(clip_a)
			// Add clip audio filterchain's output as concat filterchain's input.
			h.concatFC.AddInputByOutput(clip_a, 0)
		}

		// Increase segment count.
		n += 1
	}

	// Add ED.
	if err := h.addImageClip(h.ED, "ed"); err != nil {
		return nil, fmt.Errorf("add ED error: %v", err)
	}
	n += 1

	// Create concat filters.
	concat := ""
	if h.KeepOriginalAudio || len(h.BGMs) == 0 {
		concat = fmt.Sprintf("concat=n=%d:v=1:a=1", n)
	} else {
		concat = fmt.Sprintf("concat=n=%d:v=1:a=0", n)
	}

	// Chain concat filters.
	h.concatFC.Chain(concat)

	// Add concat filterchain to filtergraph.
	h.ffmpeg.Chain(h.concatFC)

	// Background music filterchain.
	var bgmFC *ffcmd.FilterChain

	// Check if there's BGM(background music).
	bgmNum := len(h.BGMs)
	switch bgmNum {
	case 0:
	case 1:
		bgmFC = ffcmd.NewFilterChain("[bgm]")
		// Add BGM as ffmpeg command input.
		id := h.ffmpeg.AddInput(h.BGMs[0])
		// Add input for bgm filter.
		bgmFC.AddInputByID(id, "a", 0)
	default:
		bgmFC = ffcmd.NewFilterChain("[bgm]")

		for _, f := range h.BGMs {
			// Add BGM as ffmpeg command input.
			id := h.ffmpeg.AddInput(f)
			// Add input for bgm concat filterchain.
			bgmFC.AddInputByID(id, "a", 0)
		}

		// Concat multiple BGMs to one.
		concat := fmt.Sprintf("concat=n=%d:v=0:a=1", bgmNum)
		bgmFC.Chain(concat)
	}

	if bgmFC != nil {
		// Add BGM chainfilter to filtergraph.
		h.ffmpeg.Chain(bgmFC)

		// Keep original audio
		if h.KeepOriginalAudio {
			// Create filterchain to merge BGM and original audio streams.
			amergeFC := ffcmd.NewFilterChain("[merged_a]")
			// Add BGM filterchain's output as first input.
			amergeFC.AddInputByOutput(bgmFC, 0)
			// Add Concat filterchain's audio output as second input.
			amergeFC.AddInputByOutput(h.concatFC, 1)

			// Create amerge filter.
			amerge := "amerge=inputs=2"

			// Create pan filter.
			pan := "pan=stereo|c0<c0+c2|c1<c1+c3"

			// Chain filters.
			amergeFC.Chain(amerge).Chain(pan)

			// Add merge BGM filterchain to filtergraph.
			h.ffmpeg.Chain(amergeFC)

			// Select output stream: amerge filterchain's output.
			h.ffmpeg.MapByOutput(amergeFC, 0)
		} else {
			// Select output stream: BGM filterchain's output.
			h.ffmpeg.MapByOutput(bgmFC, 0)
		}
	} else {
		// Select output stream: concat filterchain's audio output.
		h.ffmpeg.MapByOutput(h.concatFC, 1)
	}

	// Select output streams.
	// If none stream is selected, it'll auto select last filterchain's labeled outputs.
	h.ffmpeg.MapByOutput(h.concatFC, 0)

	str, _ := h.ffmpeg.String()

	log.Printf("********* str:\n%s", str)

	return h.ffmpeg, nil
}

// Make generates the FFmpeg command then run it to make the highlights video.
// ctx: context.Context to stop the command.
// dir: dir to run the ffmpeg command. It'll search media files in the dir when use relative paths.
// stdout: standard output of the ffmpeg command.
// stderr: standard error of the ffmpeg command.
func (h *Highlights) Make(ctx context.Context, dir string, stdout, stderr io.Writer) error {
	// Generate FFmpeg command.
	ffmpeg, err := h.FFmpegCmd()
	if err != nil {
		return err
	}

	// Get exec.Cmd
	cmd, err := ffcmd.CommandContext(ctx, ffmpeg)
	if err != nil {
		return err
	}

	// To stop the process and its subprocesses,
	// request that the process group id be set (Setpgid: true) to the PID of the newly spawned process (Pgid: 0).
	cmd.SysProcAttr = &syscall.SysProcAttr{
		Setpgid: true,
	}

	cmd.Dir = dir
	cmd.Stdout = stdout
	cmd.Stderr = stderr
	// cmd.Cancel will run when ctx is done.
	cmd.Cancel = func() error {
		// Kill all processes in the group via `kill -9 -$PGID`.
		// Note the "-" to signal the group.
		return syscall.Kill(-cmd.Process.Pid, syscall.SIGKILL)
	}

	if err = cmd.Run(); err != nil {
		return err
	}

	return nil
}
